// What is new, which is the report no field can contain.
//
// Asked for on 2026-09-09: "you make report on only fields that user selected,
// but the most important report is about new appearing fields and market, tool,
// platform."
//
// Every other report on this site answers "what happened in X", where X is a
// category somebody wrote down in advance. This one answers "what is here that
// was not", which cannot be filed under a category by definition -- a genuinely
// new thing arrives without a field and gets tagged with whichever existing
// label its words happened to match.
//
// NOTHING HERE IS GENERATED BY A MODEL. The three lists are the pipeline's own
// verdicts -- the event classifier's `launch` and `market`, and names read out
// of those headlines lexically -- so this page works on a day when every
// provider is rate-limited, which is the day it was written.

import { wrap, pageHead, empty, escapeHtml, truncate } from './html.ts';
import { crumbsFor } from './nav.ts';
import { whatsNew, type NewThing, type NewName } from '../analysis/whatsnew.ts';

/** A day, as a person says it. */
function niceDay(day: string): string {
  return new Date(`${day}T00:00:00Z`).toLocaleDateString('en-GB',
    { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });
}

/**
 * One story, as a line.
 *
 * First-party is marked here for the same reason it is marked everywhere else:
 * a launch announced by its own vendor is authoritative about what shipped and
 * worthless as evidence that anybody wanted it, and a funding round reported by
 * the company raising the money is a press release.
 */
function line(t: NewThing): string {
  return `<li>
    <a href="/read/${escapeHtml(t.id)}">${escapeHtml(truncate(t.title, 110))}</a>
    <span class="muted">${escapeHtml(t.source)} &middot; ${escapeHtml(t.when)}${
  t.independent ? '' : ' &middot; <span class="bf-fp">says so itself</span>'}</span>
  </li>`;
}

function nameCard(n: NewName): string {
  return `<li>
    <a href="/search?q=${encodeURIComponent(n.name)}">${escapeHtml(n.name)}</a>
    <span class="muted">${n.sources === 1 ? 'one source'
    : `${n.sources} sources`} &middot; ${escapeHtml(n.stories[0]!.when)}</span>
    <ul class="mv-elsewhere">${n.stories.map((s) => `<li>
      <a href="/read/${escapeHtml(s.id)}">${escapeHtml(truncate(s.title, 96))}</a>
      <span class="muted">${escapeHtml(s.source)}</span></li>`).join('')}</ul>
  </li>`;
}

/**
 * The window this page covers.
 *
 * Seven days rather than one, and the difference matters for this page alone:
 * a field briefing describes a day because it is written once a day, and
 * "what is new" is a question about a period. One day of launches is six
 * items and reads as an accident of timing; a week is a shape.
 */
export const NEW_DAYS = 7;

export async function renderWhatsNew(days = NEW_DAYS): Promise<string> {
  const to = new Date();
  const from = new Date(to.getTime() - days * 86_400_000);
  const w = await whatsNew(from.toISOString(), to.toISOString()).catch(() => null);

  const crumbs = crumbsFor('/new', 'What is new');
  if (!w || (w.launches.length + w.market.length + w.names.length) === 0) {
    return wrap(`
      ${pageHead('What is new', `Nothing introduced in the last ${days} days`, { crumbs })}
      ${empty('No launch and no market move reached this archive in the window. '
        + 'That is a statement about what these sources published and what this '
        + 'archive caught, not about the industry.', 'sparkle')}`);
  }

  return wrap(`
    ${pageHead('What is new',
    `Introduced, funded or first named in the last ${days} days`, { crumbs })}

    <p class="note"><b>This is the only report here that is not about a field.</b>
      Everything else answers &ldquo;what happened in X&rdquo;, where X is a
      category written down in advance &mdash; and a genuinely new thing arrives
      without one. Nothing on this page was written by a model: these are the
      pipeline&rsquo;s own verdicts about which stories introduce something
      rather than update it.</p>

    ${w.names.length === 0 ? '' : `
      <h2 class="sect">Names this archive had never seen</h2>
      <p class="note">Pulled out of the headlines below, and in none of the
        registries this archive holds &mdash; not the taxonomy, not the emerging
        ledger. A name carried by two publishers is corroborated; one is a claim.
        <b>This is a weaker test than it looks:</b> it can only find a name that
        somebody put in a headline in a form a pattern recognises, so an absence
        here means nothing at all.</p>
      <ul class="mv-new-names">${w.names.map(nameCard).join('')}</ul>`}

    ${w.market.length === 0 ? '' : `
      <h2 class="sect">Money and ownership moved</h2>
      <p class="note">Who was funded, who bought whom, and at what number
        &mdash; the second of this archive&rsquo;s two targets, and the one it
        was blind to until the venture press came off the host blocklist on
        2026-09-09.</p>
      <ul class="bf-cites">${w.market.map(line).join('')}</ul>`}

    ${w.launches.length === 0 ? '' : `
      <h2 class="sect">Introduced, not updated</h2>
      <p class="note">The event classifier&rsquo;s own verdict that a story
        introduces something rather than changing something that existed.
        ${w.totals.launches > w.launches.length
    ? `${w.totals.launches - w.launches.length} more were not listed.` : ''}</p>
      <ul class="bf-cites">${w.launches.map(line).join('')}</ul>`}

    <h2 class="sect">What this cannot tell you</h2>
    <div class="mv-caveat">
      <p><b>A launch is a claim that something is new, made by whoever published
        it.</b> This page passes that claim on with its source attached and does
        not check it. Where the source speaks for the subject, it says so.</p>
      <p><b>Nothing here is counted as a magnitude.</b> How many launches this
        archive caught in a week is a fact about its feed list, so the lists are
        shown and never totalled into a trend.</p>
      <p><b>The strong version of this page needs a model.</b> The emerging
        ledger reads names out of prose rather than out of headlines and can find
        something no headline named; it has been stalled since 23 June with
        3,064 stories unscanned, because every provider is rate-limited.</p>
    </div>`);
}
