// Taxonomy, part two.
//
// The first 367 entries covered the spine; these fill the gaps that showed up in
// real collected data -- the fields the classifier kept reaching for and the
// vocabulary check kept rejecting. Same rules as part one: closed vocabulary,
// hand-verified, docs_url only where certain, blank rather than plausible.
//
// Row shape is identical: [slug, name, parent, category, aliases, repo, docs]

import type { StackRow } from './stacks.ts';

export const LANGUAGES_EXTRA: StackRow[] = [
  ['ada',          'Ada',            'languages', 'language', 'spark-ada', '', ''],
  ['apl',          'APL',            'languages', 'language', 'dyalog', '', ''],
  ['awk',          'AWK',            'languages', 'language', 'gawk', '', ''],
  ['ballerina',    'Ballerina',      'languages', 'language', 'ballerina-lang', 'ballerina-platform/ballerina-lang', ''],
  ['coffeescript', 'CoffeeScript',   'javascript','language', '', '', ''],
  ['dlang',       'D',              'languages', 'language', 'dlang', 'dlang/dmd', ''],
  ['delphi',       'Delphi',         'languages', 'language', 'object-pascal pascal', '', ''],
  ['elm',          'Elm',            'javascript','language', 'elm-lang', '', ''],
  ['forth',        'Forth',          'languages', 'language', '', '', ''],
  ['hack',    'Hack',           'php',       'language', 'hacklang hhvm', 'facebook/hhvm', ''],
  ['idris',        'Idris',          'haskell',   'language', 'idris2', '', ''],
  ['janet',      'Janet',          'languages', 'language', 'janet-lang', 'janet-lang/janet', ''],
  ['kdb-q',          'q / kdb+',       'languages', 'language', 'kdb kx-systems', '', ''],
  ['lisp',         'Lisp',           'languages', 'language', 'common-lisp sbcl racket scheme', '', ''],
  ['matlab',       'MATLAB',         'languages', 'language', 'octave simulink', '', ''],
  ['odin',         'Odin',           'languages', 'language', 'odin-lang', 'odin-lang/Odin', ''],
  ['prolog',       'Prolog',         'languages', 'language', 'swi-prolog', '', ''],
  ['purescript',   'PureScript',     'haskell',   'language', '', 'purescript/purescript', ''],
  ['rescript',       'ReScript',       'ocaml',     'language', 'rescript reasonml', 'rescript-lang/rescript-compiler', ''],
  ['roc',          'Roc',            'languages', 'language', 'roc-lang', '', ''],
  ['sass',         'Sass',           'css',       'language', 'scss', 'sass/dart-sass', ''],
  ['tcl',          'Tcl',            'languages', 'language', 'tk', '', ''],
  ['typst',        'Typst',          'languages', 'tooling',  '', 'typst/typst', ''],
  ['unison',       'Unison',         'languages', 'language', 'unison-lang', '', ''],
  ['vala',         'Vala',           'languages', 'language', '', '', ''],
  ['verilog',      'Verilog',        'fpga',      'language', 'systemverilog', '', ''],
  ['vhdl',         'VHDL',           'fpga',      'language', '', '', ''],
  ['visual-basic', 'Visual Basic',   'csharp',    'language', 'vb-net vba', '', ''],
  ['zsh',          'Zsh',            'bash',      'tooling',  'oh-my-zsh', '', ''],
];

export const FRONTEND_EXTRA: StackRow[] = [
  ['tanstack',     'TanStack',       'javascript','library',  'react-query tanstack-query tanstack-router', 'TanStack/query', ''],
  ['redux',        'Redux',          'react',     'library',  'redux-toolkit rtk', 'reduxjs/redux', ''],
  ['zustand',      'Zustand',        'react',     'library',  '', 'pmndrs/zustand', ''],
  ['mobx',         'MobX',           'react',     'library',  '', 'mobxjs/mobx', ''],
  ['threejs',     'Three.js',       'webgl',     'library',  'threejs', 'mrdoob/three.js', ''],
  ['d3',           'D3',             'javascript','library',  'd3js data-driven-documents', 'd3/d3', ''],
  ['chartjs',      'Chart.js',       'javascript','library',  '', 'chartjs/Chart.js', ''],
  ['echarts',      'ECharts',        'javascript','library',  'apache-echarts', 'apache/echarts', ''],
  ['leaflet',      'Leaflet',        'javascript','library',  '', 'Leaflet/Leaflet', ''],
  ['mapbox',       'Mapbox',         'javascript','library',  'maplibre', '', ''],
  ['radix',        'Radix UI',       'react',     'library',  'radix-ui', 'radix-ui/primitives', ''],
  ['shadcn',       'shadcn/ui',      'react',     'library',  'shadcn-ui', '', ''],
  ['mui',          'MUI',            'react',     'library',  'material-ui', 'mui/material-ui', ''],
  ['ant-design',   'Ant Design',     'react',     'library',  'antd', 'ant-design/ant-design', ''],
  ['chakra',       'Chakra UI',      'react',     'library',  '', 'chakra-ui/chakra-ui', ''],
  ['emotion',      'Emotion',        'css',       'library',  'styled-components css-in-js', '', ''],
  ['postcss',      'PostCSS',        'css',       'tooling',  'autoprefixer', 'postcss/postcss', ''],
  ['unocss',       'UnoCSS',         'css',       'framework','', 'unocss/unocss', ''],
  ['gsap',         'GSAP',           'javascript','library',  'greensock', '', ''],
  ['framer-motion','Framer Motion',  'react',     'library',  'motion-one', '', ''],
  ['pnpm',         'pnpm',           'nodejs',    'tooling',  '', 'pnpm/pnpm', ''],
  ['yarn',         'Yarn',           'nodejs',    'tooling',  'yarnpkg', 'yarnpkg/berry', ''],
  ['npm',          'npm',            'nodejs',    'tooling',  'npmjs node-package-manager', 'npm/cli', ''],
  ['turborepo',    'Turborepo',      'javascript','tooling',  'turbo-repo', 'vercel/turborepo', ''],
  ['nx',           'Nx',             'javascript','tooling',  'nrwl', 'nrwl/nx', ''],
  ['rspack',       'Rspack',         'javascript','tooling',  '', 'web-infra-dev/rspack', ''],
  ['oxc',          'Oxc',            'javascript','tooling',  'oxlint', 'oxc-project/oxc', ''],
  ['rolldown',     'Rolldown',       'javascript','tooling',  '', 'rolldown/rolldown', ''],
  ['web-components','Web Components', 'web-platform','web',    'custom-elements shadow-dom', '', ''],
  ['ionic',     'Ionic',          'mobile',    'framework','ionic-framework', 'ionic-team/ionic-framework', ''],
];

export const BACKEND_EXTRA: StackRow[] = [
  ['drizzle',      'Drizzle ORM',    'typescript','library',  'drizzle-orm', 'drizzle-team/drizzle-orm', ''],
  ['prisma',       'Prisma',         'typescript','library',  '', 'prisma/prisma', ''],
  ['typeorm',      'TypeORM',        'typescript','library',  '', 'typeorm/typeorm', ''],
  ['sqlalchemy',   'SQLAlchemy',     'python',    'library',  '', 'sqlalchemy/sqlalchemy', ''],
  ['alembic',      'Alembic',        'python',    'tooling',  '', '', ''],
  ['pydantic',     'Pydantic',       'python',    'library',  '', 'pydantic/pydantic', ''],
  ['celery',       'Celery',         'python',    'library',  '', 'celery/celery', ''],
  ['uv',    'uv',             'python',    'tooling',  'astral-uv', 'astral-sh/uv', ''],
  ['ruff',         'Ruff',           'python',    'tooling',  '', 'astral-sh/ruff', ''],
  ['poetry',       'Poetry',         'python',    'tooling',  '', 'python-poetry/poetry', ''],
  ['litestar',     'Litestar',       'python',    'framework','starlite', 'litestar-org/litestar', ''],
  ['starlette',    'Starlette',      'python',    'framework','uvicorn asgi', 'encode/starlette', ''],
  ['gunicorn',     'Gunicorn',       'python',    'tooling',  'wsgi', '', ''],
  ['sidekiq',      'Sidekiq',        'ruby',      'library',  '', 'sidekiq/sidekiq', ''],
  ['hotwire',      'Hotwire',        'rails',     'framework','turbo stimulus', '', ''],
  ['hibernate',    'Hibernate',      'java',      'library',  'jpa', '', ''],
  ['netty',        'Netty',          'java',      'library',  '', 'netty/netty', ''],
  ['tomcat',       'Tomcat',         'java',      'infra',    'apache-tomcat', '', ''],
  ['maven',        'Maven',          'java',      'tooling',  'apache-maven', '', ''],
  ['gradle',       'Gradle',         'java',      'tooling',  '', 'gradle/gradle', ''],
  ['graalvm',      'GraalVM',        'java',      'runtime',  'native-image', 'oracle/graal', ''],
  ['entity-framework','Entity Framework','csharp','library',  'ef-core', 'dotnet/efcore', ''],
  ['blazor',       'Blazor',         'csharp',    'framework','', '', ''],
  ['sqlx',         'SQLx',           'rust',      'library',  '', 'launchbadge/sqlx', ''],
  ['serde',        'Serde',          'rust',      'library',  '', 'serde-rs/serde', ''],
  ['clap',         'clap',           'rust',      'library',  '', 'clap-rs/clap', ''],
  ['diesel',     'Diesel',         'rust',      'library',  'diesel-rs', 'diesel-rs/diesel', ''],
  ['entgo',          'Ent',            'go',        'library',  'entgo', 'ent/ent', ''],
  ['cobra',        'Cobra',          'go',        'library',  'spf13-cobra', 'spf13/cobra', ''],
  ['connect-rpc',      'Connect RPC',    'grpc',      'library',  'connectrpc buf', 'connectrpc/connect-go', ''],
  ['trpc',         'tRPC',           'typescript','library',  '', 'trpc/trpc', ''],
  ['apollo', 'Apollo',         'graphql',   'library',  'apollo-server apollo-client', 'apollographql/apollo-server', ''],
  ['hasura',       'Hasura',         'graphql',   'infra',    '', 'hasura/graphql-engine', ''],
  ['socket-io','Socket.IO',     'websockets','library',  'socketio', 'socketio/socket.io', ''],
  ['bullmq',       'BullMQ',         'nodejs',    'library',  'bull-queue', 'taskforcesh/bullmq', ''],
  ['encore',      'Encore',         'backend',   'framework','encore-dev', 'encoredev/encore', ''],
];

export const DATA_EXTRA: StackRow[] = [
  ['dremio',       'Dremio',         'data',  'data',  '', '', ''],
  ['starrocks',    'StarRocks',      'data',  'db',    '', 'StarRocks/starrocks', ''],
  ['doris',        'Apache Doris',   'data',  'db',    '', 'apache/doris', ''],
  ['pinot',        'Apache Pinot',   'data',  'db',    '', 'apache/pinot', ''],
  ['druid',        'Apache Druid',   'data',  'db',    '', 'apache/druid', ''],
  ['hbase',        'Apache HBase',   'data',  'db',    '', 'apache/hbase', ''],
  ['hive',         'Apache Hive',    'data',  'data',  '', 'apache/hive', ''],
  ['nifi',         'Apache NiFi',    'data',  'data',  '', 'apache/nifi', ''],
  ['beam',         'Apache Beam',    'data',  'data',  '', 'apache/beam', ''],
  ['samza',        'Apache Samza',   'data',  'data',  '', '', ''],
  ['debezium',     'Debezium',       'data',  'data',  'cdc change-data-capture', 'debezium/debezium', ''],
  ['airbyte',      'Airbyte',        'data',  'data',  '', 'airbytehq/airbyte', ''],
  ['fivetran',     'Fivetran',       'data',  'data',  '', '', ''],
  ['great-expectations','Great Expectations','data','tooling','data-quality', 'great-expectations/great_expectations', ''],
  ['sqlmesh',    'SQLMesh',        'data',  'tooling','sqlmesh', 'TobikoData/sqlmesh', ''],
  ['metabase',     'Metabase',       'data',  'tooling','', 'metabase/metabase', ''],
  ['superset',     'Apache Superset','data',  'tooling','', 'apache/superset', ''],
  ['looker',       'Looker',         'data',  'tooling','lookml', '', ''],
  ['tableau',      'Tableau',        'data',  'tooling','', '', ''],
  ['powerbi',      'Power BI',       'data',  'tooling','', '', ''],
  ['bigquery',     'BigQuery',       'gcp',   'db',    '', '', ''],
  ['snowflake',    'Snowflake',      'data',  'db',    '', '', ''],
  ['databricks',   'Databricks',     'data',  'data',  'unity-catalog', '', ''],
  ['redshift',     'Redshift',       'aws',   'db',    'amazon-redshift', '', ''],
  ['athena',       'Athena',         'aws',   'data',  'amazon-athena', '', ''],
  ['hudi',  'Hudi',           'data',  'data',  'apache-hudi', 'apache/hudi', ''],
  ['datafusion',   'DataFusion',     'data',  'data',  'arrow-datafusion', 'apache/datafusion', ''],
  ['materialize','Materialize', 'data',  'db',    'materializeinc', 'MaterializeInc/materialize', ''],
  ['risingwave',   'RisingWave',     'data',  'db',    '', 'risingwavelabs/risingwave', ''],
  ['redis-streams',     'Redis Streams',  'redis', 'data',  'streams', '', ''],
];

export const AI_EXTRA: StackRow[] = [
  ['peft','PEFT',          'fine-tuning','library','lora-peft', 'huggingface/peft', ''],
  ['trl-rlhf',          'TRL',            'fine-tuning','library','rlhf-trl', 'huggingface/trl', ''],
  ['axolotl',      'Axolotl',        'fine-tuning','tooling','', 'axolotl-ai-cloud/axolotl', ''],
  ['unsloth',      'Unsloth',        'fine-tuning','tooling','', 'unslothai/unsloth', ''],
  ['deepspeed',    'DeepSpeed',      'ai',    'library','', 'deepspeedai/DeepSpeed', ''],
  ['megatron',     'Megatron-LM',    'ai',    'library','', 'NVIDIA/Megatron-LM', ''],
  ['sglang',       'SGLang',         'ai',    'tooling','', 'sgl-project/sglang', ''],
  ['tensorrt',     'TensorRT',       'nvidia','tooling','tensorrt-llm', 'NVIDIA/TensorRT-LLM', ''],
  ['onnx',         'ONNX',           'ai',    'protocol','onnxruntime', 'onnx/onnx', ''],
  ['mlx',          'MLX',            'apple-silicon','framework','apple-mlx', 'ml-explore/mlx', ''],
  ['ggml',         'GGML',           'ai',    'library','gguf-format', 'ggml-org/ggml', ''],
  ['lm-studio',    'LM Studio',      'ai',    'tooling','', '', ''],
  ['openrouter',   'OpenRouter',     'llm',   'ai',    '', '', ''],
  ['groq',         'Groq',           'ai',    'hardware','lpu', '', ''],
  ['cerebras',     'Cerebras',       'ai',    'hardware','wafer-scale', '', ''],
  ['tpu',          'TPU',            'gpu',   'hardware','google-tpu tensor-processing-unit', '', ''],
  ['kimi','Kimi',          'llm',   'ai',    'moonshot kimi-k2', '', ''],
  ['grok',         'Grok',           'llm',   'ai',    'xai grok-4', '', ''],
  ['cohere',    'Cohere',         'llm',   'ai',    'command-r', '', ''],
  ['phi',          'Phi',            'llm',   'ai',    'microsoft-phi', '', ''],
  ['gemma',        'Gemma',          'llm',   'ai',    'google-gemma', '', ''],
  ['embeddings',   'Embeddings',     'ai',    'practice','vector-embeddings sentence-transformers', '', ''],
  ['prompt-engineering','Prompt Engineering','ai','practice','prompting few-shot chain-of-thought', '', ''],
  ['evals',        'Model Evaluation','ai',   'practice','evals benchmarks mmlu swe-bench', '', ''],
  ['guardrails',   'AI Guardrails',  'ai-safety','practice','content-filtering jailbreak', '', ''],
  ['synthetic-data','Synthetic Data','ai',    'practice','', '', ''],
  ['multimodal',   'Multimodal',     'ai',    'practice','vision-language vlm', '', ''],
  ['speech',       'Speech',         'ai',    'practice','tts stt asr voice-cloning', '', ''],
  ['recsys',       'Recommender Systems','ai','practice','recommendation-engine', '', ''],
  ['computer-vision','Computer Vision','ai',  'practice','cv object-detection yolo segmentation', '', ''],
  ['nlp',          'NLP',            'ai',    'practice','natural-language-processing ner', '', ''],
  ['reinforcement-learning','Reinforcement Learning','ai','practice','rl ppo dqn', '', ''],
  ['agent-protocols','Agent Protocols','ai-agents','protocol','a2a agent-to-agent acp', '', ''],
  ['vector-search','Vector Search',  'ai',    'practice','ann hnsw similarity-search', '', ''],
  ['ai-coding-tools',    'AI Coding Tools','ai',    'tooling','copilot cursor windsurf codex aider claude-code', '', ''],
];

export const INFRA_EXTRA: StackRow[] = [
  ['k3s',          'k3s',            'kubernetes','infra','rancher-k3s', 'k3s-io/k3s', ''],
  ['talos',        'Talos Linux',    'kubernetes','os',  'talos-os', 'siderolabs/talos', ''],
  ['kubevirt',     'KubeVirt',       'kubernetes','infra','', 'kubevirt/kubevirt', ''],
  ['knative',      'Knative',        'kubernetes','infra','', 'knative/serving', ''],
  ['crossplane',   'Crossplane',     'kubernetes','infra','', 'crossplane/crossplane', ''],
  ['kustomize',    'Kustomize',      'kubernetes','tooling','', 'kubernetes-sigs/kustomize', ''],
  ['kubernetes-operators', 'Operators',      'kubernetes','practice','operator-pattern crd', '', ''],
  ['gitops',       'GitOps',         'devops','practice','', '', ''],
  ['buildkit',     'BuildKit',       'docker','tooling','buildx', 'moby/buildkit', ''],
  ['buildpacks',   'Buildpacks',     'devops','tooling','cloud-native-buildpacks', '', ''],
  ['devbox',   'Devbox',         'nixos', 'tooling','jetify-devbox', 'jetify-com/devbox', ''],
  ['dagger',      'Dagger',         'devops','tooling','dagger-io', 'dagger/dagger', ''],
  ['jenkins',      'Jenkins',        'ci-cd', 'tooling','', 'jenkinsci/jenkins', ''],
  ['circleci',     'CircleCI',       'ci-cd', 'tooling','', '', ''],
  ['buildkite',    'Buildkite',      'ci-cd', 'tooling','', '', ''],
  ['woodpecker-ci',        'Woodpecker CI',  'ci-cd', 'tooling','woodpecker drone-ci', 'woodpecker-ci/woodpecker', ''],
  ['opentofu-registry',    'OpenTofu Registry','terraform','tooling','', '', ''],
  ['packer',       'Packer',         'infra', 'tooling','hashicorp-packer', 'hashicorp/packer', ''],
  ['vagrant',      'Vagrant',        'infra', 'tooling','', 'hashicorp/vagrant', ''],
  ['proxmox',      'Proxmox',        'infra', 'infra','pve', '', ''],
  ['kvm',      'KVM',            'infra', 'infra','libvirt qemu virtualization', '', ''],
  ['firecracker',  'Firecracker',    'infra', 'infra','microvm', 'firecracker-microvm/firecracker', ''],
  ['wasmtime',     'Wasmtime',       'wasm',  'runtime','bytecodealliance', 'bytecodealliance/wasmtime', ''],
  ['wasmer',       'Wasmer',         'wasm',  'runtime','', 'wasmerio/wasmer', ''],
  ['spin',         'Spin',           'wasm',  'framework','fermyon-spin', 'spinframework/spin', ''],
  ['zfs',          'ZFS',            'infra', 'infra','openzfs', 'openzfs/zfs', ''],
  ['btrfs',        'Btrfs',          'linux', 'os',   '', '', ''],
  ['nfs',          'NFS',            'infra', 'protocol','network-file-system', '', ''],
  ['s3',           'S3',             'aws',   'infra','object-storage', '', ''],
  ['cdn',          'CDN',            'infra', 'infra','content-delivery-network edge-caching', '', ''],
  ['load-balancing','Load Balancing','infra', 'practice','reverse-proxy', '', ''],
  ['service-mesh', 'Service Mesh',   'infra', 'practice','', '', ''],
  ['chaos-engineering','Chaos Engineering','sre','practice','chaos-monkey fault-injection', '', ''],
  ['capacity-planning','Capacity Planning','sre','practice','autoscaling', '', ''],
  ['incident-management','On-Call',  'sre',   'practice','pagerduty oncall postmortems', '', ''],
  ['finops',       'FinOps',         'cloud', 'practice','cloud-cost cost-optimization', '', ''],
  ['edge-computing','Edge Computing','cloud', 'practice','edge-runtime', '', ''],
  ['multi-cloud',  'Multi-Cloud',    'cloud', 'practice','hybrid-cloud', '', ''],
  ['sovereign-cloud','Sovereign Cloud','cloud','domain','data-residency', '', ''],
];

export const SECURITY_EXTRA: StackRow[] = [
  ['sbom',         'SBOM',           'supply-chain-security','practice','cyclonedx spdx', '', ''],
  ['sigstore',     'Sigstore',       'supply-chain-security','tooling','cosign rekor', 'sigstore/cosign', ''],
  ['slsa',         'SLSA',           'supply-chain-security','practice','provenance', '', ''],
  ['dependency-scanning',   'Dependency Scanning','supply-chain-security','tooling','dependabot renovate snyk', '', ''],
  ['semgrep',      'Semgrep',        'appsec','tooling','sast-semgrep', 'semgrep/semgrep', ''],
  ['codeql',       'CodeQL',         'appsec','tooling','', 'github/codeql', ''],
  ['trivy',        'Trivy',          'appsec','tooling','', 'aquasecurity/trivy', ''],
  ['burp',         'Burp Suite',     'pentesting','tooling','portswigger', '', ''],
  ['metasploit',   'Metasploit',     'pentesting','tooling','', 'rapid7/metasploit-framework', ''],
  ['nmap',         'Nmap',           'pentesting','tooling','', 'nmap/nmap', ''],
  ['wireshark',    'Wireshark',      'security','tooling','packet-capture pcap', '', ''],
  ['ghidra',       'Ghidra',         'security','tooling','reverse-engineering', 'NationalSecurityAgency/ghidra', ''],
  ['yara',         'YARA',           'malware','tooling','', 'VirusTotal/yara', ''],
  ['mitre-attack', 'MITRE ATT&CK',   'security','practice','ttp', '', ''],
  ['soc',          'SOC',            'security','practice','siem soar blue-team detection-engineering', '', ''],
  ['edr',          'EDR / XDR',      'security','tooling','endpoint-detection', '', ''],
  ['waf',          'WAF',            'appsec','tooling','web-application-firewall', '', ''],
  ['ddos',         'DDoS',           'security','security','denial-of-service', '', ''],
  ['phishing',     'Phishing',       'security','security','social-engineering bec', '', ''],
  ['supply-chain-attack','Supply Chain Attacks','supply-chain-security','security','dependency-confusion typosquat', '', ''],
  ['zero-day',     'Zero-Day',       'cve',   'security','0day in-the-wild', '', ''],
  ['kev',          'Known Exploited Vulnerabilities','cve','security','cisa-kev actively-exploited', '', ''],
  ['cvss',         'CVSS',           'cve',   'practice','epss severity-scoring', '', ''],
  ['bug-bounty',   'Bug Bounty',     'security','practice','hackerone bugcrowd responsible-disclosure', '', ''],
  ['passkeys',     'Passkeys',       'identity','protocol','webauthn fido2', '', ''],
  ['mtls',         'mTLS',           'tls',   'protocol','mutual-tls', '', ''],
  ['hsm',          'HSM',            'cryptography','hardware','hardware-security-module tpm secure-enclave', '', ''],
  ['homomorphic',  'Homomorphic Encryption','cryptography','practice','fhe', '', ''],
  ['zero-knowledge','Zero-Knowledge Proofs','cryptography','practice','zk zk-snark zk-rollup', '', ''],
  ['confidential-computing','Confidential Computing','security','practice','enclaves sgx sev-snp', '', ''],
  ['gdpr',         'GDPR',           'privacy','domain','dsgvo', '', ''],
  ['ccpa',         'CCPA',           'privacy','domain','cpra', '', ''],
  ['nis2',         'NIS2',           'security','domain','cyber-resilience-act cra', '', ''],
  ['soc2',         'SOC 2',          'security','practice','iso-27001 compliance fedramp', '', ''],
];

export const PLATFORM_EXTRA: StackRow[] = [
  ['turso', 'Turso',          'sqlite','db',    'libsql-turso', 'tursodatabase/turso', ''],
  ['upstash',      'Upstash',        'redis', 'cloud', '', '', ''],
  ['clerk',        'Clerk',          'identity','cloud','', '', ''],
  ['auth0',        'Auth0',          'identity','cloud','okta', '', ''],
  ['keycloak',     'Keycloak',       'identity','infra','', 'keycloak/keycloak', ''],
  ['stripe',       'Stripe',         'backend','cloud','payments', '', ''],
  ['twilio',       'Twilio',         'backend','cloud','sms-api', '', ''],
  ['email-delivery',     'Email Delivery', 'backend','cloud','sendgrid postmark resend ses', '', ''],
  ['sentry',       'Sentry',         'observability','tooling','error-tracking', 'getsentry/sentry', ''],
  ['datadog',      'Datadog',        'observability','tooling','', '', ''],
  ['new-relic',    'New Relic',      'observability','tooling','', '', ''],
  ['honeycomb',    'Honeycomb',      'observability','tooling','', '', ''],
  ['elastic-apm',  'Elastic APM',    'observability','tooling','', '', ''],
  ['signoz','SigNoz',        'observability','tooling','', 'SigNoz/signoz', ''],
  ['uptime',       'Uptime Monitoring','observability','tooling','statuspage synthetic-monitoring', '', ''],
  ['feature-flags','Feature Flags',  'practice','tooling','launchdarkly unleash flagsmith', '', ''],
  ['ab-testing',   'A/B Testing',    'practice','practice','experimentation split-testing', '', ''],
  ['analytics',    'Product Analytics','practice','tooling','posthog amplitude mixpanel plausible', '', ''],
  ['cms',          'CMS',            'web-platform','tooling','headless-cms contentful sanity strapi payload', '', ''],
  ['wordpress',    'WordPress',      'php',   'framework','woocommerce gutenberg', '', ''],
  ['shopify',      'Shopify',        'web-platform',   'cloud', 'hydrogen', '', ''],
  ['salesforce',   'Salesforce',     'backend','cloud','apex', '', ''],
  ['sap',          'SAP',            'backend','cloud','abap', '', ''],
  ['servicenow',   'ServiceNow',     'backend','cloud','', '', ''],
  ['atlassian',    'Atlassian',      'practice','tooling','jira confluence bitbucket', '', ''],
  ['slack-platform','Slack',         'practice','tooling','slack-api bolt', '', ''],
  ['discord-dev',  'Discord',        'practice','tooling','discord-api', '', ''],
  ['notion',       'Notion',         'practice','tooling','notion-api', '', ''],
  ['figma',        'Figma',          'practice','tooling','design-tokens', '', ''],
  ['obsidian',     'Obsidian',       'practice','tooling','pkm zettelkasten', '', ''],
];

export const HARDWARE_EXTRA: StackRow[] = [
  ['hbm',          'HBM',            'hardware','hardware','high-bandwidth-memory hbm3 hbm4', '', ''],
  ['ddr5',         'DDR5',           'hardware','hardware','ddr4 memory dram', '', ''],
  ['nvme',         'NVMe',           'hardware','hardware','ssd storage-hardware', '', ''],
  ['cxl',          'CXL',            'hardware','protocol','compute-express-link', '', ''],
  ['pcie',         'PCIe',           'hardware','protocol','pci-express gen5 gen6', '', ''],
  ['usb',          'USB',            'hardware','protocol','usb4 thunderbolt', '', ''],
  ['wifi',         'Wi-Fi',          'hardware','protocol','wifi6 wifi7 802-11', '', ''],
  ['bluetooth',    'Bluetooth',      'hardware','protocol','ble', '', ''],
  ['5g',           '5G',             'hardware','protocol','6g cellular oran', '', ''],
  ['satellite',    'Satellite Internet','hardware','domain','starlink leo', '', ''],
  ['photonics',    'Silicon Photonics','hardware','hardware','optical-interconnect co-packaged-optics', '', ''],
  ['semiconductor-manufacturing',          'Semiconductor Manufacturing','hardware','domain','euv tsmc asml foundry lithography 2nm', '', ''],
  ['npu',          'NPU',            'hardware','hardware','neural-processing-unit ai-accelerator', '', ''],
  ['qualcomm',   'Qualcomm',       'arm',  'hardware','snapdragon', '', ''],
  ['mediatek',     'MediaTek',       'arm',  'hardware','dimensity', '', ''],
  ['broadcom',     'Broadcom',       'hardware','hardware','tomahawk networking-silicon', '', ''],
  ['memory-vendors',       'Memory Vendors', 'hardware','hardware','micron sk-hynix samsung-memory', '', ''],
  ['cooling',      'Data Centre Cooling','datacenter','domain','liquid-cooling immersion pue', '', ''],
  ['power-grid',   'Power & Energy', 'datacenter','domain','grid nuclear-smr renewable-energy', '', ''],
  ['robotics',     'Robotics',       'hardware','domain','humanoid ros autonomous-vehicles', '', ''],
  ['drones',       'Drones',         'hardware','domain','uav', '', ''],
  ['ar-vr',        'AR / VR',        'hardware','domain','xr vision-pro quest spatial-computing', '', ''],
  ['wearables',    'Wearables',      'hardware','domain','smartwatch smart-glasses', '', ''],
  ['3d-printing',  '3D Printing',    'hardware','domain','additive-manufacturing', '', ''],
  ['biotech',      'Bio-computing',  'hardware','domain','dna-storage organoid', '', ''],
];

export const PRACTICE_EXTRA: StackRow[] = [
  ['api-design',   'API Design',     'architecture','practice','rest-design versioning idempotency', '', ''],
  ['event-sourcing','Event Sourcing','event-driven','practice','', '', ''],
  ['distributed-transactions',         'Distributed Transactions','architecture','practice','saga-pattern two-phase-commit', '', ''],
  ['consensus',    'Consensus',      'architecture','practice','raft paxos distributed-consensus', '', ''],
  ['caching',      'Caching',        'performance','practice','cache-invalidation memoization', '', ''],
  ['rate-limiting','Rate Limiting',  'architecture','practice','throttling backpressure', '', ''],
  ['reliability',  'Reliability',    'sre',   'practice','retries circuit-breaker timeouts', '', ''],
  ['schema-migration',   'Schema Migration','data',  'practice','zero-downtime-migration', '', ''],
  ['sharding',     'Sharding',       'data',  'practice','partitioning replication', '', ''],
  ['data-modeling','Data Modeling',  'data',  'practice','normalization star-schema', '', ''],
  ['developer-tooling',   'Developer Tooling','devex','tooling','lsp language-server tree-sitter', '', ''],
  ['terminal',     'Terminals',      'devex', 'tooling','tmux alacritty ghostty wezterm', '', ''],
  ['editors',      'Editors',        'devex', 'tooling','vscode neovim vim emacs zed jetbrains', '', ''],
  ['debugging',    'Debugging',      'practice','practice','gdb lldb profiler flamegraph', '', ''],
  ['static-analysis','Static Analysis','practice','practice','linting type-checking formal-verification', '', ''],
  ['property-testing','Property Testing','testing','practice','quickcheck hypothesis fuzz-testing', '', ''],
  ['contract-testing','Contract Testing','testing','practice','pact consumer-driven', '', ''],
  ['load-testing', 'Load Testing',   'testing','practice','k6 jmeter locust stress-testing', '', ''],
  ['a11y-testing','Accessibility Testing','accessibility','practice','axe screen-reader', '', ''],
  ['i18n',         'Internationalization','practice','practice','i18n l10n localization unicode-text', '', ''],
  ['design-systems','Design Systems','frontend','practice','component-library storybook-ds', '', ''],
  ['tech-debt',    'Technical Debt', 'refactoring','practice','legacy-migration strangler-fig', '', ''],
  ['code-generation','Code Generation','practice','practice','codegen scaffolding ast-transform', '', ''],
  ['monorepo',     'Monorepos',      'practice','practice','polyrepo workspace', '', ''],
  ['release-engineering','Release Engineering','ci-cd','practice','semver changelog canary-release blue-green', '', ''],
  ['slos',      'SLOs',           'sre',   'practice','error-budget sli slo', '', ''],
  ['postmortems',  'Postmortems',    'sre',   'practice','blameless incident-review rca', '', ''],
  ['docs-as-code', 'Docs as Code',   'documentation','practice','mkdocs docusaurus sphinx', '', ''],
  ['adr',          'Architecture Decision Records','architecture','practice','adr rfc-process', '', ''],
  ['pair-programming','Pair Programming','practice','practice','mob-programming', '', ''],
  ['code-ownership','Code Ownership','practice','practice','codeowners team-topologies', '', ''],
  ['engineering-management','Engineering Management','practice','domain','tech-lead staff-engineer ic-track', '', ''],
  ['developer-productivity','Developer Productivity','devex','practice','dora-metrics space-framework', '', ''],
  ['open-source-sustainability','Open Source Sustainability','open-source','domain','maintainer-burnout sponsorship foundation', '', ''],
  ['relicensing','Relicensing','licensing','domain','bsl sspl fair-source source-available', '', ''],
  ['standards-orgs','Standards Bodies','standards','domain','ietf w3c iso ecma nist', '', ''],
  ['antitrust',    'Antitrust',      'tech-policy','domain','dma dsa regulation-eu', '', ''],
  ['export-controls','Export Controls','tech-policy','domain','chip-sanctions entity-list', '', ''],
  ['digital-identity-policy','Digital Identity Policy','tech-policy','domain','eidas age-verification', '', ''],
  ['content-moderation','Content Moderation','tech-policy','domain','trust-and-safety', '', ''],
  ['remote-work',  'Remote Work',    'hiring','domain','distributed-teams rto', '', ''],
  ['layoffs',      'Layoffs',        'hiring','domain','job-market tech-layoffs', '', ''],
  ['interviewing', 'Interviewing',   'hiring','practice','system-design-interview leetcode', '', ''],
  ['compensation', 'Compensation',   'hiring','domain','equity rsu salary-bands', '', ''],
  ['freelancing',  'Freelancing',    'hiring','domain','contracting consulting indie-hacking', '', ''],
  ['acquisitions', 'M&A',            'startups','domain','acquisition merger', '', ''],
  ['ipo',          'IPOs',           'startups','domain','public-offering', '', ''],
  ['venture-capital','Venture Capital','startups','domain','vc seed-round series-a valuation', '', ''],
  ['bootstrapping','Bootstrapping',  'startups','domain','profitable saas-metrics', '', ''],
  ['developer-relations','Developer Relations','practice','domain','devrel advocacy community-building', '', ''],
];

export const EXTRA_ROWS: StackRow[] = [
  ...LANGUAGES_EXTRA,
  ...FRONTEND_EXTRA,
  ...BACKEND_EXTRA,
  ...DATA_EXTRA,
  ...AI_EXTRA,
  ...INFRA_EXTRA,
  ...SECURITY_EXTRA,
  ...PLATFORM_EXTRA,
  ...HARDWARE_EXTRA,
  ...PRACTICE_EXTRA,
];
