// Hand-curated taxonomy. Everything here is curated:true; anything the discovery
// loop adds later carries curated:false and is displayed differently until a human
// reviews it (spec 9.2).
//
// docs_url and repo_url are filled in ONLY where they are known with certainty. A
// model will usually get React's docs URL right and occasionally invent a
// plausible wrong one, which is worse than blank in a permanent record. Blank is
// the honest default; the UI shows a gap, not a lie.
//
// Row shape: [slug, name, parent, category, aliases, repo(owner/name), docs_url]
// release_feed_url is derived mechanically from repo -- github releases.atom.

export type StackRow = [
  slug: string,
  name: string,
  parent: string,
  category: string,
  aliases: string,
  repo: string,
  docs: string,
];

const ROOTS: StackRow[] = [
  ['languages',   'Programming Languages', '', 'domain', 'plt language-design', '', ''],
  ['frontend',    'Frontend',              '', 'domain', 'front-end client-side ui', '', ''],
  ['backend',     'Backend',               '', 'domain', 'back-end server-side', '', ''],
  ['mobile',      'Mobile',                '', 'domain', 'mobile-development', '', ''],
  ['data',        'Data',                  '', 'domain', 'data-engineering analytics database databases db rdbms datastore storage', '', ''],
  ['ai',          'AI / ML',               '', 'domain', 'artificial-intelligence machine-learning ml genai generative-ai llms', '', ''],
  ['security',    'Security',              '', 'domain', 'infosec cybersecurity appsec vulnerability privacy-security', '', ''],
  ['infra',       'Infrastructure',        '', 'domain', 'infrastructure sysadmin', '', ''],
  ['devops',      'DevOps',                '', 'domain', 'sre platform-engineering', '', ''],
  ['cloud',       'Cloud',                 '', 'domain', 'cloud-computing', '', ''],
  ['os',          'Operating Systems',     '', 'domain', 'operating-system kernel-space', '', ''],
  ['hardware',    'Hardware',              '', 'domain', 'silicon chips', '', ''],
  ['web-platform','Web Platform',          '', 'domain', 'web-standards browser', '', ''],
  ['gamedev',     'Game Development',      '', 'domain', 'games game-engines', '', ''],
  ['embedded',    'Embedded',              '', 'domain', 'firmware microcontroller', '', ''],
  ['practice',    'Engineering Practice',  '', 'domain', 'software-engineering craft', '', ''],
];

const LANGUAGES: StackRow[] = [
  ['javascript',  'JavaScript', 'languages', 'language', 'js ecmascript es2015 vanilla-js', '', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript'],
  ['typescript',  'TypeScript', 'javascript', 'language', 'ts tsc', 'microsoft/TypeScript', 'https://www.typescriptlang.org/docs/'],
  ['python',      'Python',     'languages', 'language', 'py cpython python3', 'python/cpython', 'https://docs.python.org/3/'],
  ['rust',        'Rust',       'languages', 'language', 'rustlang rust-lang cargo', 'rust-lang/rust', 'https://doc.rust-lang.org/book/'],
  ['go',          'Go',         'languages', 'language', 'golang', 'golang/go', 'https://go.dev/doc/'],
  ['java',        'Java',       'languages', 'language', 'jvm openjdk jdk', 'openjdk/jdk', ''],
  ['kotlin',      'Kotlin',     'java',      'language', 'kotlinlang', 'JetBrains/kotlin', 'https://kotlinlang.org/docs/home.html'],
  ['scala',       'Scala',      'java',      'language', 'scala3 scala-lang', 'scala/scala3', ''],
  ['clojure',     'Clojure',    'java',      'language', 'clj clojurescript', 'clojure/clojure', ''],
  ['groovy',      'Groovy',     'java',      'language', 'apache-groovy', 'apache/groovy', ''],
  ['swift',       'Swift',      'languages', 'language', 'swiftlang', 'swiftlang/swift', ''],
  ['objective-c', 'Objective-C','languages', 'language', 'objc', '', ''],
  ['c',           'C',          'languages', 'language', 'c99 c11 c17 c23 ansi-c', '', ''],
  ['cpp',         'C++',        'languages', 'language', 'c-plus-plus cplusplus cpp20 cpp23 cpp26', '', 'https://en.cppreference.com/w/'],
  ['csharp',      'C#',         'languages', 'language', 'c-sharp', 'dotnet/csharplang', ''],
  ['fsharp',      'F#',         'csharp',    'language', 'f-sharp', 'dotnet/fsharp', ''],
  ['ruby',        'Ruby',       'languages', 'language', 'ruby-lang mri', 'ruby/ruby', ''],
  ['php',         'PHP',        'languages', 'language', 'php8 php-lang', 'php/php-src', 'https://www.php.net/docs.php'],
  ['elixir',      'Elixir',     'languages', 'language', 'elixir-lang', 'elixir-lang/elixir', ''],
  ['erlang',      'Erlang',     'languages', 'language', 'otp beam erlang-otp', 'erlang/otp', ''],
  ['gleam',       'Gleam',      'erlang',    'language', 'gleam-lang', 'gleam-lang/gleam', ''],
  ['haskell',     'Haskell',    'languages', 'language', 'ghc cabal', 'ghc/ghc', ''],
  ['ocaml',       'OCaml',      'languages', 'language', 'caml opam', 'ocaml/ocaml', ''],
  ['zig',         'Zig',        'languages', 'language', 'ziglang', 'ziglang/zig', 'https://ziglang.org/documentation/master/'],
  ['nim',         'Nim',        'languages', 'language', 'nim-lang', 'nim-lang/Nim', ''],
  ['crystal',     'Crystal',    'languages', 'language', 'crystal-lang', 'crystal-lang/crystal', ''],
  ['lua',         'Lua',        'languages', 'language', 'luajit', '', ''],
  ['perl',        'Perl',       'languages', 'language', 'perl5 raku', '', ''],
  ['r',           'R',          'languages', 'language', 'r-lang rstats cran', '', ''],
  ['julia',       'Julia',      'languages', 'language', 'julialang', 'JuliaLang/julia', ''],
  ['dart',        'Dart',       'languages', 'language', 'dart-lang', 'dart-lang/sdk', ''],
  ['solidity',    'Solidity',   'languages', 'language', 'evm-language', 'ethereum/solidity', ''],
  ['mojo',        'Mojo',       'python',    'language', 'modular-mojo', '', ''],
  ['sql',         'SQL',        'languages', 'language', 'ansi-sql', '', ''],
  ['bash',        'Bash / Shell','languages','language', 'shell sh zsh posix-shell', '', ''],
  ['powershell',  'PowerShell', 'languages', 'language', 'pwsh', 'PowerShell/PowerShell', ''],
  ['assembly',    'Assembly',   'languages', 'language', 'asm x86-asm arm-asm', '', ''],
  ['fortran',     'Fortran',    'languages', 'language', 'gfortran', '', ''],
  ['wasm',        'WebAssembly','languages', 'runtime',  'webassembly wasi wasm32', '', 'https://webassembly.org/'],
];

const FRONTEND: StackRow[] = [
  ['react',       'React',      'frontend', 'framework', 'reactjs react.js react-dom', 'facebook/react', 'https://react.dev/'],
  ['nextjs',      'Next.js',    'react',    'framework', 'next next-js vercel-next', 'vercel/next.js', 'https://nextjs.org/docs'],
  ['remix',       'Remix',      'react',    'framework', 'remix-run react-router-7', 'remix-run/remix', ''],
  ['react-router','React Router','react',   'library',   'reactrouter', 'remix-run/react-router', ''],
  ['vue',         'Vue.js',     'frontend', 'framework', 'vuejs vue3 vue.js', 'vuejs/core', 'https://vuejs.org/guide/introduction.html'],
  ['nuxt',        'Nuxt',       'vue',      'framework', 'nuxtjs nuxt3', 'nuxt/nuxt', ''],
  ['angular',     'Angular',    'frontend', 'framework', 'angularjs angular2 ng', 'angular/angular', 'https://angular.dev/'],
  ['svelte',      'Svelte',     'frontend', 'framework', 'sveltejs', 'sveltejs/svelte', 'https://svelte.dev/docs'],
  ['sveltekit',   'SvelteKit',  'svelte',   'framework', 'svelte-kit', 'sveltejs/kit', ''],
  ['solidjs',     'SolidJS',    'frontend', 'framework', 'solid-js solid', 'solidjs/solid', ''],
  ['qwik',        'Qwik',       'frontend', 'framework', 'builder-qwik', 'QwikDev/qwik', ''],
  ['preact',      'Preact',     'frontend', 'library',   'preactjs', 'preactjs/preact', ''],
  ['lit',         'Lit',        'frontend', 'library',   'lit-element lit-html web-components', 'lit/lit', ''],
  ['htmx',        'htmx',       'frontend', 'library',   'htmx.org', 'bigskysoftware/htmx', ''],
  ['alpinejs',    'Alpine.js',  'frontend', 'library',   'alpine alpinejs', 'alpinejs/alpine', ''],
  ['astro',       'Astro',      'frontend', 'framework', 'astrojs astro-build', 'withastro/astro', ''],
  ['ember',       'Ember.js',   'frontend', 'framework', 'emberjs', 'emberjs/ember.js', ''],
  ['tailwindcss', 'Tailwind CSS','css',     'framework', 'tailwind tailwind-css', 'tailwindlabs/tailwindcss', 'https://tailwindcss.com/docs'],
  ['bootstrap',   'Bootstrap',  'css',      'framework', 'twitter-bootstrap', 'twbs/bootstrap', ''],
  ['vite',        'Vite',       'frontend', 'tooling',   'vitejs', 'vitejs/vite', 'https://vitejs.dev/guide/'],
  ['webpack',     'webpack',    'frontend', 'tooling',   'webpack5', 'webpack/webpack', ''],
  ['rollup',      'Rollup',     'frontend', 'tooling',   'rollupjs', 'rollup/rollup', ''],
  ['esbuild',     'esbuild',    'frontend', 'tooling',   '', 'evanw/esbuild', ''],
  ['parcel',      'Parcel',     'frontend', 'tooling',   'parceljs', 'parcel-bundler/parcel', ''],
  ['turbopack',   'Turbopack',  'frontend', 'tooling',   'turbo-pack', 'vercel/turborepo', ''],
  ['babel',       'Babel',      'javascript','tooling',  'babeljs', 'babel/babel', ''],
  ['eslint',      'ESLint',     'javascript','tooling',  'es-lint', 'eslint/eslint', ''],
  ['prettier',    'Prettier',   'javascript','tooling',  '', 'prettier/prettier', ''],
  ['biome',       'Biome',      'javascript','tooling',  'rome-tools biomejs', 'biomejs/biome', ''],
  ['storybook',   'Storybook',  'frontend', 'tooling',   'storybookjs', 'storybookjs/storybook', ''],
];

const WEB_PLATFORM: StackRow[] = [
  ['html',        'HTML',       'web-platform', 'web', 'html5 whatwg-html', '', ''],
  ['css',         'CSS',        'web-platform', 'web', 'css3 stylesheets', '', ''],
  ['webgpu',      'WebGPU',     'web-platform', 'web', 'wgsl', '', ''],
  ['webgl',       'WebGL',      'web-platform', 'web', '', '', ''],
  ['webrtc',      'WebRTC',     'web-platform', 'protocol', 'rtc', '', ''],
  ['websockets',  'WebSockets', 'web-platform', 'protocol', 'websocket ws', '', ''],
  ['service-workers','Service Workers','web-platform','web','sw pwa-workers', '', ''],
  ['pwa',         'Progressive Web Apps','web-platform','web','progressive-web-app', '', ''],
  ['accessibility','Accessibility','web-platform','practice','a11y wcag aria', '', ''],
  ['browsers',    'Browsers',   'web-platform', 'web', 'chromium firefox safari webkit gecko blink', '', ''],
];

const PROTOCOLS: StackRow[] = [
  ['http',        'HTTP',       'web-platform', 'protocol', 'http1 http2 rest-over-http', '', ''],
  ['http3',       'HTTP/3',     'http',         'protocol', 'h3', '', ''],
  ['quic',        'QUIC',       'http3',        'protocol', '', '', ''],
  ['dns',         'DNS',        'infra',        'protocol', 'doh dot dnssec', '', ''],
  ['tcp',         'TCP/IP',     'infra',        'protocol', 'tcp ip networking', '', ''],
  ['ipv6',        'IPv6',       'tcp',          'protocol', '', '', ''],
  ['grpc',        'gRPC',       'backend',      'protocol', 'grpc-web', 'grpc/grpc', ''],
  ['graphql',     'GraphQL',    'backend',      'protocol', 'gql apollo-graphql', 'graphql/graphql-spec', ''],
  ['openapi',     'OpenAPI',    'backend',      'protocol', 'swagger oas', 'OAI/OpenAPI-Specification', ''],
  ['protobuf',    'Protocol Buffers','data',    'protocol', 'proto3 protocol-buffers', 'protocolbuffers/protobuf', ''],
  ['mcp',         'Model Context Protocol','ai','protocol', 'model-context-protocol mcp-server', 'modelcontextprotocol/servers', ''],
  ['activitypub', 'ActivityPub','web-platform', 'protocol', 'fediverse', '', ''],
  ['atproto',     'AT Protocol','web-platform', 'protocol', 'at-protocol bluesky-protocol', 'bluesky-social/atproto', ''],
  ['matrix',      'Matrix',     'web-platform', 'protocol', 'matrix-org', 'matrix-org/synapse', ''],
];

const BACKEND: StackRow[] = [
  ['nodejs',      'Node.js',    'javascript', 'runtime',   'node node-js nodejs22', 'nodejs/node', 'https://nodejs.org/docs/latest/api/'],
  ['deno',        'Deno',       'javascript', 'runtime',   'denoland', 'denoland/deno', ''],
  ['bun',         'Bun',        'javascript', 'runtime',   'bunjs oven-bun', 'oven-sh/bun', ''],
  ['express',     'Express',    'nodejs',     'framework', 'expressjs', 'expressjs/express', ''],
  ['fastify',     'Fastify',    'nodejs',     'framework', '', 'fastify/fastify', ''],
  ['nestjs',      'NestJS',     'nodejs',     'framework', 'nest', 'nestjs/nest', ''],
  ['hono',        'Hono',       'javascript', 'framework', 'honojs', 'honojs/hono', ''],
  ['django',      'Django',     'python',     'framework', 'django-rest-framework drf', 'django/django', 'https://docs.djangoproject.com/'],
  ['flask',       'Flask',      'python',     'framework', 'pallets-flask', 'pallets/flask', ''],
  ['fastapi',     'FastAPI',    'python',     'framework', 'fast-api', 'fastapi/fastapi', ''],
  ['rails',       'Ruby on Rails','ruby',     'framework', 'rubyonrails rails7 rails8', 'rails/rails', ''],
  ['sinatra',     'Sinatra',    'ruby',       'framework', '', 'sinatra/sinatra', ''],
  ['laravel',     'Laravel',    'php',        'framework', '', 'laravel/laravel', ''],
  ['symfony',     'Symfony',    'php',        'framework', '', 'symfony/symfony', ''],
  ['spring',      'Spring',     'java',       'framework', 'spring-boot springframework', 'spring-projects/spring-boot', ''],
  ['quarkus',     'Quarkus',    'java',       'framework', '', 'quarkusio/quarkus', ''],
  ['micronaut',   'Micronaut',  'java',       'framework', '', 'micronaut-projects/micronaut-core', ''],
  ['ktor',        'Ktor',       'kotlin',     'framework', '', 'ktorio/ktor', ''],
  ['aspnet',      'ASP.NET Core','csharp',    'framework', 'aspnetcore dotnet-aspnet', 'dotnet/aspnetcore', ''],
  ['dotnet',      '.NET',       'csharp',     'runtime',   'dotnet-core net8 net9', 'dotnet/runtime', ''],
  ['gin',         'Gin',        'go',         'framework', 'gin-gonic', 'gin-gonic/gin', ''],
  ['echo',        'Echo',       'go',         'framework', 'labstack-echo', 'labstack/echo', ''],
  ['fiber',       'Fiber',      'go',         'framework', 'gofiber', 'gofiber/fiber', ''],
  ['actix',       'Actix Web',  'rust',       'framework', 'actix-web', 'actix/actix-web', ''],
  ['axum',        'Axum',       'rust',       'framework', 'tokio-axum', 'tokio-rs/axum', ''],
  ['tokio',       'Tokio',      'rust',       'runtime',   'tokio-rs async-rust', 'tokio-rs/tokio', ''],
  ['phoenix',     'Phoenix',    'elixir',     'framework', 'phoenix-liveview liveview', 'phoenixframework/phoenix', ''],
];

const DATABASES: StackRow[] = [
  ['postgresql',  'PostgreSQL', 'data', 'db', 'postgres pg psql postgres17 postgres18', 'postgres/postgres', 'https://www.postgresql.org/docs/'],
  ['pgvector',    'pgvector',   'postgresql', 'db', 'pg-vector', 'pgvector/pgvector', ''],
  ['timescaledb', 'TimescaleDB','postgresql', 'db', 'timescale', 'timescale/timescaledb', ''],
  ['mysql',       'MySQL',      'data', 'db', 'mysql8', '', ''],
  ['mariadb',     'MariaDB',    'mysql','db', '', '', ''],
  ['sqlite',      'SQLite',     'data', 'db', 'sqlite3 libsql', '', 'https://www.sqlite.org/docs.html'],
  ['duckdb',      'DuckDB',     'data', 'db', 'duck-db', 'duckdb/duckdb', ''],
  ['mongodb',     'MongoDB',    'data', 'db', 'mongo', 'mongodb/mongo', ''],
  ['redis',       'Redis',      'data', 'db', 'redis-stack', 'redis/redis', ''],
  ['valkey',      'Valkey',     'redis','db', 'valkey-io', 'valkey-io/valkey', ''],
  ['cassandra',   'Cassandra',  'data', 'db', 'apache-cassandra', 'apache/cassandra', ''],
  ['scylladb',    'ScyllaDB',   'cassandra','db','scylla', 'scylladb/scylladb', ''],
  ['cockroachdb', 'CockroachDB','data', 'db', 'cockroach crdb', 'cockroachdb/cockroach', ''],
  ['tidb',        'TiDB',       'data', 'db', 'pingcap-tidb', 'pingcap/tidb', ''],
  ['yugabyte',    'YugabyteDB', 'data', 'db', 'yugabyte-db', 'yugabyte/yugabyte-db', ''],
  ['clickhouse',  'ClickHouse', 'data', 'db', 'click-house', 'ClickHouse/ClickHouse', ''],
  ['influxdb',    'InfluxDB',   'data', 'db', 'influx', 'influxdata/influxdb', ''],
  ['questdb',     'QuestDB',    'data', 'db', 'quest-db', 'questdb/questdb', ''],
  ['elasticsearch','Elasticsearch','data','db','elastic es-search', 'elastic/elasticsearch', ''],
  ['opensearch',  'OpenSearch', 'elasticsearch','db','open-search', 'opensearch-project/OpenSearch', ''],
  ['meilisearch', 'Meilisearch','data', 'db', 'meili', 'meilisearch/meilisearch', ''],
  ['typesense',   'Typesense',  'data', 'db', '', 'typesense/typesense', ''],
  ['neo4j',       'Neo4j',      'data', 'db', 'cypher-query', 'neo4j/neo4j', ''],
  ['surrealdb',   'SurrealDB',  'data', 'db', 'surreal', 'surrealdb/surrealdb', ''],
  ['dynamodb',    'DynamoDB',   'aws',  'db', 'dynamo', '', ''],
  ['supabase',    'Supabase',   'postgresql','db','supabase-io', 'supabase/supabase', ''],
  ['neon',        'Neon',       'postgresql','db','neon-tech neondb', 'neondatabase/neon', ''],
  ['planetscale', 'PlanetScale','mysql','db', 'vitess-cloud', '', ''],
  ['vitess',      'Vitess',     'mysql','db', '', 'vitessio/vitess', ''],
  ['qdrant',      'Qdrant',     'data', 'db', 'vector-db-qdrant', 'qdrant/qdrant', ''],
  ['weaviate',    'Weaviate',   'data', 'db', '', 'weaviate/weaviate', ''],
  ['milvus',      'Milvus',     'data', 'db', '', 'milvus-io/milvus', ''],
  ['pinecone',    'Pinecone',   'data', 'db', '', '', ''],
  ['chroma',      'Chroma',     'data', 'db', 'chromadb', 'chroma-core/chroma', ''],
  ['lancedb',     'LanceDB',    'data', 'db', 'lance', 'lancedb/lancedb', ''],
  ['etcd',        'etcd',       'infra','db', '', 'etcd-io/etcd', ''],
  ['minio',       'MinIO',      'infra','db', 's3-compatible', 'minio/minio', ''],
  ['ceph',        'Ceph',       'infra','db', '', 'ceph/ceph', ''],
];

const DATA_ENG: StackRow[] = [
  ['kafka',       'Apache Kafka','data','infra', 'apache-kafka kafka-streams', 'apache/kafka', ''],
  ['redpanda',    'Redpanda',   'kafka','infra', 'vectorized-redpanda', 'redpanda-data/redpanda', ''],
  ['rabbitmq',    'RabbitMQ',   'data', 'infra', 'amqp', 'rabbitmq/rabbitmq-server', ''],
  ['nats',        'NATS',       'data', 'infra', 'nats-io jetstream', 'nats-io/nats-server', ''],
  ['pulsar',      'Apache Pulsar','data','infra','apache-pulsar', 'apache/pulsar', ''],
  ['spark',       'Apache Spark','data','data',  'apache-spark pyspark', 'apache/spark', ''],
  ['flink',       'Apache Flink','data','data',  'apache-flink', 'apache/flink', ''],
  ['airflow',     'Apache Airflow','data','data','apache-airflow', 'apache/airflow', ''],
  ['dagster',     'Dagster',    'data', 'data',  '', 'dagster-io/dagster', ''],
  ['prefect',     'Prefect',    'data', 'data',  '', 'PrefectHQ/prefect', ''],
  ['dbt',         'dbt',        'data', 'data',  'dbt-core data-build-tool', 'dbt-labs/dbt-core', ''],
  ['trino',       'Trino',      'data', 'data',  'presto-sql', 'trinodb/trino', ''],
  ['iceberg',     'Apache Iceberg','data','data','table-format-iceberg', 'apache/iceberg', ''],
  ['delta-lake',  'Delta Lake', 'data', 'data',  'deltalake', 'delta-io/delta', ''],
  ['arrow',       'Apache Arrow','data','data',  'apache-arrow arrow-flight', 'apache/arrow', ''],
  ['parquet',     'Parquet',    'data', 'data',  'apache-parquet', '', ''],
  ['polars',      'Polars',     'data', 'data',  'py-polars', 'pola-rs/polars', ''],
  ['pandas',      'pandas',     'python','data', 'py-pandas', 'pandas-dev/pandas', ''],
  ['numpy',       'NumPy',      'python','data', 'np', 'numpy/numpy', ''],
  ['temporal',    'Temporal',   'backend','infra','temporal-io workflow-engine', 'temporalio/temporal', ''],
];

const AI: StackRow[] = [
  ['llm',           'Large Language Models','ai','ai', 'llms language-model foundation-model', '', ''],
  ['pytorch',       'PyTorch',    'ai', 'framework', 'torch', 'pytorch/pytorch', 'https://pytorch.org/docs/stable/index.html'],
  ['tensorflow',    'TensorFlow', 'ai', 'framework', 'tf keras-backend', 'tensorflow/tensorflow', ''],
  ['jax',           'JAX',       'ai', 'framework', 'google-jax flax', 'jax-ml/jax', ''],
  ['keras',         'Keras',     'ai', 'framework', '', 'keras-team/keras', ''],
  ['huggingface',   'Hugging Face','ai','ai', 'hf transformers-hub', 'huggingface/transformers', ''],
  ['langchain',     'LangChain', 'ai', 'framework', 'langchain-py langgraph', 'langchain-ai/langchain', ''],
  ['llamaindex',    'LlamaIndex','ai', 'framework', 'gpt-index', 'run-llama/llama_index', ''],
  ['ollama',        'Ollama',    'ai', 'tooling',   '', 'ollama/ollama', ''],
  ['vllm',          'vLLM',      'ai', 'tooling',   'v-llm', 'vllm-project/vllm', ''],
  ['llama-cpp',     'llama.cpp', 'ai', 'tooling',   'llamacpp ggml gguf', 'ggml-org/llama.cpp', ''],
  ['openai',        'OpenAI',    'llm','ai', 'gpt gpt-4 gpt-5 chatgpt o-series dall-e', '', ''],
  ['anthropic',     'Anthropic Claude','llm','ai', 'claude claude-code sonnet opus haiku', '', ''],
  ['gemini',        'Google Gemini','llm','ai', 'bard google-gemini gemma', '', ''],
  ['llama',         'Llama',     'llm','ai', 'meta-llama llama3 llama4', 'meta-llama/llama', ''],
  ['mistral',       'Mistral',   'llm','ai', 'mistral-ai mixtral', '', ''],
  ['qwen',          'Qwen',      'llm','ai', 'qwen2 qwen3 alibaba-qwen tongyi', 'QwenLM/Qwen', ''],
  ['deepseek',      'DeepSeek',  'llm','ai', 'deepseek-v3 deepseek-r1', 'deepseek-ai/DeepSeek-V3', ''],
  ['stable-diffusion','Stable Diffusion','ai','ai','sd sdxl diffusion-models', '', ''],
  ['comfyui',       'ComfyUI',   'stable-diffusion','tooling','comfy', 'comfyanonymous/ComfyUI', ''],
  ['whisper',       'Whisper',   'ai', 'ai', 'openai-whisper speech-to-text', 'openai/whisper', ''],
  ['rag',           'RAG',       'ai', 'practice', 'retrieval-augmented-generation', '', ''],
  ['fine-tuning',   'Fine-tuning','ai','practice', 'lora qlora peft sft rlhf', '', ''],
  ['ai-agents',     'AI Agents', 'ai', 'practice', 'agentic agent-frameworks tool-use', '', ''],
  ['ai-safety',     'AI Safety', 'ai', 'practice', 'alignment interpretability red-teaming', '', ''],
  ['ai-policy',     'AI Policy', 'ai', 'domain',   'ai-regulation ai-act ai-governance', '', ''],
  ['mlops',         'MLOps',     'ai', 'practice', 'ml-ops model-deployment', '', ''],
  ['scikit-learn',  'scikit-learn','python','library','sklearn', 'scikit-learn/scikit-learn', ''],
  ['xgboost',       'XGBoost',   'ai', 'library',   'gradient-boosting', 'dmlc/xgboost', ''],
  ['ray',           'Ray',       'ai', 'infra',     'ray-project anyscale', 'ray-project/ray', ''],
];

const SECURITY: StackRow[] = [
  ['cve',           'CVEs / Vulnerabilities','security','security','cve vulnerability nvd 0day zero-day', '', ''],
  ['supply-chain-security','Supply Chain Security','security','security','sbom slsa dependency-confusion typosquatting', '', ''],
  ['cryptography',  'Cryptography','security','security','crypto encryption cipher', '', ''],
  ['post-quantum',  'Post-Quantum Crypto','cryptography','security','pqc kyber dilithium ml-kem', '', ''],
  ['tls',           'TLS',       'cryptography','protocol','ssl https-tls certificates lets-encrypt', '', ''],
  ['oauth',         'OAuth / OIDC','security','protocol','oauth2 openid-connect sso saml', '', ''],
  ['jwt',           'JWT',       'oauth','protocol','json-web-token', '', ''],
  ['appsec',        'Application Security','security','security','owasp xss sqli csrf ssrf', '', ''],
  ['pentesting',    'Penetration Testing','security','practice','red-team offensive-security exploit-dev', '', ''],
  ['fuzzing',       'Fuzzing',   'security','practice','afl libfuzzer oss-fuzz', '', ''],
  ['malware',       'Malware',   'security','security','ransomware botnet rootkit trojan', '', ''],
  ['incident-response','Incident Response','security','practice','dfir forensics breach', '', ''],
  ['secrets-management','Secrets Management','security','practice','vault-secrets key-management kms', '', ''],
  ['zero-trust',    'Zero Trust','security','practice','beyondcorp mtls', '', ''],
  ['privacy',       'Privacy',   'security','domain','gdpr ccpa data-protection tracking', '', ''],
  ['identity',      'Identity',  'security','domain','iam passkeys webauthn fido2 mfa', '', ''],
];

const INFRA: StackRow[] = [
  ['kubernetes',    'Kubernetes','infra','infra','k8s kube kubectl', 'kubernetes/kubernetes', 'https://kubernetes.io/docs/home/'],
  ['docker',        'Docker',    'infra','infra','dockerfile docker-compose', 'moby/moby', 'https://docs.docker.com/'],
  ['podman',        'Podman',    'infra','infra','', 'containers/podman', ''],
  ['containerd',    'containerd','infra','infra','', 'containerd/containerd', ''],
  ['helm',          'Helm',      'kubernetes','tooling','helm-charts', 'helm/helm', ''],
  ['argocd',        'Argo CD',   'kubernetes','devops','argo gitops-argo', 'argoproj/argo-cd', ''],
  ['flux',          'Flux CD',   'kubernetes','devops','fluxcd', 'fluxcd/flux2', ''],
  ['terraform',     'Terraform', 'infra','devops','hashicorp-terraform hcl tf', 'hashicorp/terraform', ''],
  ['opentofu',      'OpenTofu',  'terraform','devops','tofu', 'opentofu/opentofu', ''],
  ['pulumi',        'Pulumi',    'infra','devops','', 'pulumi/pulumi', ''],
  ['ansible',       'Ansible',   'infra','devops','ansible-playbook', 'ansible/ansible', ''],
  ['nomad',         'Nomad',     'infra','infra','hashicorp-nomad', 'hashicorp/nomad', ''],
  ['consul',        'Consul',    'infra','infra','hashicorp-consul', 'hashicorp/consul', ''],
  ['vault',         'Vault',     'security','infra','hashicorp-vault', 'hashicorp/vault', ''],
  ['nginx',         'nginx',     'infra','infra','', 'nginx/nginx', ''],
  ['caddy',         'Caddy',     'infra','infra','caddyserver', 'caddyserver/caddy', ''],
  ['haproxy',       'HAProxy',   'infra','infra','', 'haproxy/haproxy', ''],
  ['envoy',         'Envoy',     'infra','infra','envoyproxy', 'envoyproxy/envoy', ''],
  ['traefik',       'Traefik',   'infra','infra','traefik-proxy', 'traefik/traefik', ''],
  ['istio',         'Istio',     'kubernetes','infra','service-mesh-istio', 'istio/istio', ''],
  ['linkerd',       'Linkerd',   'kubernetes','infra','', 'linkerd/linkerd2', ''],
  ['cilium',        'Cilium',    'kubernetes','infra','', 'cilium/cilium', ''],
  ['ebpf',          'eBPF',      'os','infra','bpf xdp', '', ''],
  ['prometheus',    'Prometheus','devops','infra','promql', 'prometheus/prometheus', ''],
  ['grafana',       'Grafana',   'devops','infra','', 'grafana/grafana', ''],
  ['loki',          'Loki',      'grafana','infra','grafana-loki', 'grafana/loki', ''],
  ['opentelemetry', 'OpenTelemetry','devops','infra','otel otlp', 'open-telemetry/opentelemetry-specification', ''],
  ['jaeger',        'Jaeger',    'devops','infra','', 'jaegertracing/jaeger', ''],
  ['vector-logs',   'Vector',    'devops','infra','vectordev timber-vector', 'vectordotdev/vector', ''],
  ['systemd',       'systemd',   'os','infra','systemctl journald', 'systemd/systemd', ''],
];

const CLOUD: StackRow[] = [
  ['aws',           'AWS',       'cloud','cloud','amazon-web-services ec2 s3 lambda', '', ''],
  ['gcp',           'Google Cloud','cloud','cloud','google-cloud-platform gce bigquery', '', ''],
  ['azure',         'Azure',     'cloud','cloud','microsoft-azure', '', ''],
  ['cloudflare',    'Cloudflare','cloud','cloud','cf-workers workers-kv r2 durable-objects', '', ''],
  ['vercel',        'Vercel',    'cloud','cloud','', '', ''],
  ['netlify',       'Netlify',   'cloud','cloud','', '', ''],
  ['fly-io',        'Fly.io',    'cloud','cloud','flyio fly-machines', '', ''],
  ['railway',       'Railway',   'cloud','cloud','railway-app', '', ''],
  ['render',        'Render',    'cloud','cloud','render-com', '', ''],
  ['digitalocean',  'DigitalOcean','cloud','cloud','do-droplets', '', ''],
  ['hetzner',       'Hetzner',   'cloud','cloud','hetzner-cloud', '', ''],
  ['oracle-cloud',  'Oracle Cloud','cloud','cloud','oci', '', ''],
  ['serverless',    'Serverless','cloud','practice','faas edge-functions lambda-style', '', ''],
];

const OPERATING_SYSTEMS: StackRow[] = [
  ['linux',         'Linux',     'os','os','linux-kernel gnu-linux', 'torvalds/linux', ''],
  ['debian',        'Debian',    'linux','os','', '', ''],
  ['ubuntu',        'Ubuntu',    'debian','os','canonical-ubuntu', '', ''],
  ['fedora',        'Fedora',    'linux','os','', '', ''],
  ['rhel',          'RHEL',      'linux','os','red-hat-enterprise-linux centos rocky-linux alma', '', ''],
  ['arch',          'Arch Linux','linux','os','archlinux pacman', '', ''],
  ['alpine',        'Alpine Linux','linux','os','alpine-linux musl', '', ''],
  ['nixos',         'NixOS',     'linux','os','nix nixpkgs flakes', 'NixOS/nixpkgs', ''],
  ['gentoo',        'Gentoo',    'linux','os','portage', '', ''],
  ['freebsd',       'FreeBSD',   'os','os','bsd', 'freebsd/freebsd-src', ''],
  ['openbsd',       'OpenBSD',   'os','os','', '', ''],
  ['netbsd',        'NetBSD',    'os','os','', '', ''],
  ['windows',       'Windows',   'os','os','win32 windows11 wsl', '', ''],
  ['macos',         'macOS',     'os','os','osx darwin apple-macos', '', ''],
  ['ios',           'iOS',       'mobile','os','ipados apple-ios', '', ''],
  ['android',       'Android',   'mobile','os','aosp android-os', '', ''],
  ['chromeos',      'ChromeOS',  'os','os','chrome-os', '', ''],
  ['wayland',       'Wayland',   'linux','os','', '', ''],
  ['x11',           'X11',       'linux','os','xorg', '', ''],
  ['gnome',         'GNOME',     'linux','os','gtk', '', ''],
  ['kde',           'KDE',       'linux','os','plasma qt-kde', '', ''],
  ['redox',         'Redox OS',  'os','os','redox-os', '', ''],
];

const MOBILE: StackRow[] = [
  ['react-native',  'React Native','react','framework','rn expo-rn', 'facebook/react-native', ''],
  ['flutter',       'Flutter',   'dart','framework','flutter-sdk', 'flutter/flutter', ''],
  ['swiftui',       'SwiftUI',   'swift','framework','', '', ''],
  ['jetpack-compose','Jetpack Compose','kotlin','framework','compose-multiplatform', '', ''],
  ['expo',          'Expo',      'react-native','tooling','expo-go', 'expo/expo', ''],
  ['capacitor',     'Capacitor', 'mobile','framework','ionic-capacitor', 'ionic-team/capacitor', ''],
  ['tauri',         'Tauri',     'rust','framework','tauri-apps', 'tauri-apps/tauri', ''],
  ['electron',      'Electron',  'javascript','framework','electronjs', 'electron/electron', ''],
];

const HARDWARE: StackRow[] = [
  ['cpu',           'CPUs',      'hardware','hardware','processors microarchitecture', '', ''],
  ['gpu',           'GPUs',      'hardware','hardware','graphics-cards accelerators', '', ''],
  ['nvidia',        'NVIDIA',    'gpu','hardware','cuda geforce h100 blackwell', '', ''],
  ['amd',           'AMD',       'hardware','hardware','ryzen radeon rocm epyc', '', ''],
  ['intel',         'Intel',     'hardware','hardware','xeon core-ultra oneapi', '', ''],
  ['arm',           'Arm',       'hardware','hardware','aarch64 arm64 cortex', '', ''],
  ['risc-v',        'RISC-V',    'hardware','hardware','riscv rv64', '', ''],
  ['x86',           'x86',       'hardware','hardware','x86-64 amd64', '', ''],
  ['apple-silicon', 'Apple Silicon','arm','hardware','m1 m2 m3 m4 apple-m-series', '', ''],
  ['fpga',          'FPGA',      'hardware','hardware','verilog vhdl', '', ''],
  ['quantum-computing','Quantum Computing','hardware','hardware','qubits quantum qiskit', '', ''],
  ['raspberry-pi',  'Raspberry Pi','embedded','hardware','rpi', '', ''],
  ['esp32',         'ESP32',     'embedded','hardware','esp8266 espressif', '', ''],
  ['arduino',       'Arduino',   'embedded','hardware','', '', ''],
  ['iot',           'IoT',       'embedded','domain','internet-of-things smart-home matter-iot', '', ''],
  ['datacenter',    'Data Centres','hardware','domain','datacentre colo power-cooling', '', ''],
];

const GAMEDEV: StackRow[] = [
  ['unity',         'Unity',     'gamedev','framework','unity3d unity-engine', '', ''],
  ['unreal',        'Unreal Engine','gamedev','framework','ue5 unreal-engine', '', ''],
  ['godot',         'Godot',     'gamedev','framework','godot-engine gdscript', 'godotengine/godot', ''],
  ['bevy',          'Bevy',      'rust','framework','bevy-engine', 'bevyengine/bevy', ''],
  ['vulkan',        'Vulkan',    'gamedev','protocol','khronos-vulkan', '', ''],
  ['opengl',        'OpenGL',    'gamedev','protocol','glsl', '', ''],
  ['directx',       'DirectX',   'gamedev','protocol','direct3d dx12 hlsl', '', ''],
  ['metal',         'Metal',     'gamedev','protocol','apple-metal', '', ''],
];

const PRACTICE: StackRow[] = [
  ['testing',       'Testing',   'practice','practice','unit-tests integration-tests tdd e2e', '', ''],
  ['playwright',    'Playwright','testing','tooling','pw-test', 'microsoft/playwright', ''],
  ['cypress',       'Cypress',   'testing','tooling','', 'cypress-io/cypress', ''],
  ['vitest',        'Vitest',    'testing','tooling','', 'vitest-dev/vitest', ''],
  ['jest',          'Jest',      'testing','tooling','', 'jestjs/jest', ''],
  ['pytest',        'pytest',    'testing','tooling','py-test', 'pytest-dev/pytest', ''],
  ['ci-cd',         'CI/CD',     'devops','practice','continuous-integration continuous-delivery pipelines', '', ''],
  ['github-actions','GitHub Actions','ci-cd','tooling','gha actions-workflow', '', ''],
  ['git',           'Git',       'practice','tooling','version-control', 'git/git', ''],
  ['github',        'GitHub',    'git','tooling','gh', '', ''],
  ['gitlab',        'GitLab',    'git','tooling','', '', ''],
  ['observability', 'Observability','devops','practice','monitoring tracing metrics slo', '', ''],
  ['sre',           'SRE',       'devops','practice','site-reliability-engineering incident-management postmortem', '', ''],
  ['platform-engineering','Platform Engineering','devops','practice','internal-developer-platform idp', '', ''],
  ['architecture',  'Architecture','practice','practice','software-architecture system-design', '', ''],
  ['microservices', 'Microservices','architecture','practice','service-oriented', '', ''],
  ['monolith',      'Monoliths', 'architecture','practice','modular-monolith', '', ''],
  ['event-driven',  'Event-Driven Architecture','architecture','practice','eda event-sourcing cqrs', '', ''],
  ['ddd',           'Domain-Driven Design','architecture','practice','domain-driven', '', ''],
  ['performance',   'Performance','practice','practice','optimization profiling latency benchmarks', '', ''],
  ['refactoring',   'Refactoring','practice','practice','technical-debt legacy-code', '', ''],
  ['code-review',   'Code Review','practice','practice','pull-requests', '', ''],
  ['documentation', 'Documentation','practice','practice','docs-as-code technical-writing', '', ''],
  ['devex',         'Developer Experience','practice','practice','dx developer-productivity', '', ''],
  ['open-source',   'Open Source','practice','domain','oss foss maintainers', '', ''],
  ['licensing',     'Licensing',  'open-source','domain','gpl apache-license mit-license bsl relicensing', '', ''],
  ['tech-policy',   'Tech Policy','practice','domain','regulation antitrust dma standards-policy', '', ''],
  ['standards',     'Standards',  'practice','domain','ietf w3c whatwg tc39 rfc', '', ''],
  ['hiring',        'Hiring & Careers','practice','domain','interviews layoffs compensation remote-work', '', ''],
  ['startups',      'Startups',   'practice','domain','funding vc acquisitions yc', '', ''],
];

import { EXTRA_ROWS } from './stacks-extra.ts';

export const STACK_ROWS: StackRow[] = [
  ...ROOTS,
  ...LANGUAGES,
  ...FRONTEND,
  ...WEB_PLATFORM,
  ...PROTOCOLS,
  ...BACKEND,
  ...DATABASES,
  ...DATA_ENG,
  ...AI,
  ...SECURITY,
  ...INFRA,
  ...CLOUD,
  ...OPERATING_SYSTEMS,
  ...MOBILE,
  ...HARDWARE,
  ...GAMEDEV,
  ...PRACTICE,
  // Part two: the gaps that showed up in real collected data.
  ...EXTRA_ROWS,
];

export interface StackSeed {
  slug: string;
  name: string;
  parent: string | null;
  category: string;
  aliases: string[];
  repo_url: string | null;
  docs_url: string | null;
  release_feed_url: string | null;
}

export function stackSeeds(): StackSeed[] {
  return STACK_ROWS.map(([slug, name, parent, category, aliases, repo, docs]) => ({
    slug,
    name,
    parent: parent || null,
    category,
    aliases: aliases.split(' ').filter(Boolean),
    repo_url: repo ? `https://github.com/${repo}` : null,
    docs_url: docs || null,
    // Mechanical, not guessed: every GitHub repo exposes this path.
    release_feed_url: repo ? `https://github.com/${repo}/releases.atom` : null,
  }));
}
